### ISSUE TITLE
是否支持其他格式喃？

### ISSUE THREAD

**Issue by lysShub** [cxgreat2014/VBScript_DOC2PDF#4]
我对VBS和office自动化不太了解，所以想问一下作者理论上是否支持ppt，xlsx格式啊？
可以的话我就花时间学习一下。

**Comment by cxgreat2014** [comment]
您好，调用的都是COM组件进行的操作，理论上是支持的

**Comment by lysShub** [comment]
谢谢，找到文档。
https://docs.microsoft.com/zh-cn/office/vba
